[package]
name = "rust-bittorrent-client"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.138"
serde_bencode = "^0.2.4"
serde = "^1.0.0"
serde_derive = "^1.0.0"
serde_bytes = "0.11.15"
